language: python

sudo: required
dist: trusty

os: linux

python:
- '2.7'

before_install:
- sudo chmod u+x .travis/*.sh
- "/bin/bash .travis/setup.sh"

script:
- bash .travis/build.sh e3sm-unified.def
