os: linux

language: go

go:
    - "1.11"

python:
    - "3.7"

addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
    packages:
      - squashfs
    update: true

sudo: required

before_install:
    - sudo chmod u+x .travis/*.sh
    - "/bin/bash .travis/setup.sh"

script:
    - travis_wait 30 bash .travis/build.sh e3sm-unified.def
    - travis_wait 30 bash .travis/build.sh cime-env.def
