# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 13 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "E3SM-Unified" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

requirements:
  host:
    - python
  run:
    ### main packages ###
    - python
    - cdat 8.1 # [py<=36]
    # - e3sm_diags 1.6.0
    - nco 4.7.9
    - jupyter
    - ipython
    - globus-cli
    - mpas-analysis 1.2.2
    # - processflow # [py27]
    - ilamb 2.3.1 # [py27]
    - ilamb 2.4 # [py>=36]
    - livvkit 2.1.6
    - zstash 0.2.0 # [py27]
    ### dependencies ###
    - cdat_info 8.1.1
    - cdms2 3.1.2
    - cdtime 3.1.2
    - cdutil 8.1
    - genutil 8.1.1
    - vtk-cdat 8.2.0rc2.8.1
    - dv3d 8.1
    - vcs 8.1
    - vcsaddons 8.1
    - output_viewer 1.2.5
    - wk 8.1
    - thermo 8.1
    - e3sm_nex 1.0.0
    - cibots 0.2
    - xarray 0.11.3
    - dask 1.1.3
    - lxml
    - sympy
    - pyproj
    - pytest
    - shapely
    - cartopy
    - progressbar2
    - pillow
    - numpy >1.13
    - scipy
    - matplotlib
    - basemap
    - blas
    - nb_conda # [py<=36]
    - nb_conda_kernels # [py<=36]
    - plotly
    - bottleneck
    - hdf5 1.10.4
    - netcdf4 1.4.2
    - pyevtk 1.1.2
    - f90nml
    - globus-sdk
    - tabulate
    - cmocean
    - gsw
    - libnetcdf 4.6.2
    - pyflann
    - scikit-image
    - shapely

test:
  imports:
    - mpas_analysis
    # - acme_diags
  commands:
    - livv --version
    - export CDAT_ANONYMOUS_LOG=no; python -c "import vcs"
    # - processflow -v
    # - e3sm_diags -v

about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a unified conda environment for analysis of results
    from the Energy Exascale Earth System Model (E3SM).
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
