# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 13 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "E3SM-Unified" %}
{% set version = "1.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

requirements:
  host:
    - python
  run:
    ### main packages ###
    - python
    # channel: conda-forge
    - nco 4.8.1
    - jupyter
    - ipython
    - globus-cli
    - mpas-analysis 1.2.4
    - ilamb 2.3.1 # [py27]
    - ilamb 2.4 # [py>=36]
    - livvkit 2.1.6
    - geometric_features 0.1.1
    - mpas_tools 0.0.3
    - tempest-remap
    # channel: cdat/label/v81
    - cdat 8.1
    # channel: e3sm
    - e3sm_diags 1.6.1 # [py27]
    - e3sm_diags 1.7.1 # [py>=36]
    - processflow 2.2.1 # [linux and py27]
    - zstash 0.2.0 # [linux and py27]
    - zstash 0.3.0 # [linux and py>=36]
    ### dependencies ###
    # channel: cdat/lable/v81
    - cdat_info 8.1.1
    - vcsaddons 8.1
    - vtk-cdat 8.2.0rc2.8.1
    - dv3d 8.1
    - vcs 8.1
    - wk 8.1
    - e3sm_nex 1.0.0
    # channel: conda-forge
    - cdms2 3.1.2
    - cdtime 3.1.2
    - cdutil 8.1
    - genutil 8.1.1
    - output_viewer 1.3.0
    - cibots 0.3
    - xarray 0.11.3 # [py27]
    - xarray 0.12.3 # [py>=36]
    - dask 1.2.2 # [py27]
    - dask 2.1.0 # [py>=36]
    - lxml
    - sympy
    - pyproj >=1.9.6,<2.0.0
    - proj4 >=5.2.0,<6.0.0
    - pytest
    - shapely
    - cartopy
    - progressbar2
    - pillow
    - numpy >1.13
    - scipy
    - matplotlib
    - basemap
    - blas
    - nb_conda
    - nb_conda_kernels
    - plotly
    - bottleneck
    - hdf5 1.10.5
    - netcdf4 1.5.1.2
    - pyevtk 1.1.2
    - f90nml
    - globus-sdk <=1.7.1
    - tabulate
    - cmocean
    - gsw
    - libnetcdf 4.6.2
    - pyflann
    - scikit-image
    - shapely
    - eofs 1.3.1
    - pywavelets
    # dependencies of the COMPASS test-case infrastructure in MPAS
    - jigsaw
    - metis
    - pyflann
    - scikit-image
    - pyamg
    - ffmpeg
test:
  requires:
    - pytest
  imports:
    - mpas_analysis
    - acme_diags
    - ILAMB
    - zstash # [linux]
    - IPython
    - globus_cli
    - livvkit
  commands:
    - mpas_analysis --version
    - livv --version
    - export CDAT_ANONYMOUS_LOG=no; python -c "import vcs"
    - processflow -v # [linux and py27]
    - e3sm_diags --help
    - zstash --help # [linux]
    - ilamb-fetch -h
    - ilamb-run -h
    - ilamb-table -h
    - ncks --help
    - ncap2 --help
    - jupyter --help
    - jupyter nbextension list
    - ipython -h
    - ipython3 -h # [py>=36]
    - globus --help
    - GenerateCSMesh --res 64 --alt --file gravitySam.000000.3d.cubedSphere.g
about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a unified conda environment for analysis of results
    from the Energy Exascale Earth System Model (E3SM).
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
