{% set name = "globus-sdk" %}
{% set version = "1.3.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d6fc7f985a91bbb15cb3d5979d162972a0684b7552e2773c09f22c4c53076650" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - requests >=2.0.0,<3.0.0
    - six >=1.10.0,<2.0.0
  run:
    - python
    - requests >=2.0.0,<3.0.0
    - six >=1.10.0,<2.0.0

test:
  imports:
    - globus_sdk
    - globus_sdk.auth
    - globus_sdk.auth.client_types
    - globus_sdk.authorizers
    - globus_sdk.transfer
    - globus_sdk.transfer.response

about:
  home: https://github.com/globus/globus-sdk-python
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: Globus SDK for Python
  description: ".. image:: https://travis-ci.org/globus/globus-sdk-python.svg?branch=master\n    :alt: build status\n    :target: https://travis-ci.org/globus/globus-sdk-python\n\nGlobus SDK for Python\n\
    =====================\n\nThis SDK provides a convenient Pythonic interface to\n`Globus <https://www.globus.org>`_ REST APIs,\nincluding the Transfer API and the Globus Auth API.\n\nDocumentation\n-------------\n\
    \n| Full Documentation: http://globus-sdk-python.readthedocs.io/\n| Source Code: https://github.com/globus/globus-sdk-python\n| REST Documentation: https://docs.globus.org"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: 'xylar'
