{% set name = "evtk" %}
{% set version = "1.1.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  hg_url: https://bitbucket.org/pauloh/pyevtk
  hg_tag: 4e759fe

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.8.0
  run:
    - python
    - numpy >=1.8.0

test:
  imports:
    - evtk

about:
  home: https://bitbucket.org/pauloh/pyevtk
  license: FreeBSD
  license_family: BSD
  license_file: ''
  summary: Export data as binary VTK files
  description: "EVTK (Export VTK) package allows exporting data to binary VTK files for visualization and data analysis with any of the visualization packages that support VTK files, e.g. Paraview, VisIt and Mayavi."
  doc_url: 'https://bitbucket.org/pauloh/pyevtk'
  dev_url: 'https://bitbucket.org/pauloh/pyevtk'

extra:
  recipe-maintainers: 'xylar'
