{% set name = "E3SM-Unified" %}
{% set version = "1.3.1.2" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: {{ build }}

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `e3sm-unified * mpi_mpich_*` for mpich
  # `e3sm-unified * mpi_*` for any mpi
  # `e3sm-unified * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build }}"

requirements:
  host:
    - python
  run:
    ### main packages ###
    - python
    # channel: conda-forge
    - nco 4.9.5
    - jupyter
    - ipython
    - globus-cli
    - mpas-analysis 1.2.8
    - ilamb 2.5  # [mpi != 'nompi']
    - livvkit 3.0.0
    - geometric_features 0.1.11
    - mpas_tools 0.0.13
    - e3sm_diags 2.2.0
    # ncl requires the latest proj and libgdal but these conflict with rasterio
    # - ncl >=6.6.2
    # channel: e3sm
    - processflow 2.2.4  # [linux]
    - compass 0.1.11 {{ mpi_prefix }}_*
    - zstash 0.4.2  # [linux]
    ### dependencies ###
    # channel: conda-forge
    - {{ mpi }}  # [mpi != 'nompi']
    - cdat_info 8.2
    # build 10 has correct pins of libnetcdf, incorrect in earlier builds
    - cdms2 3.1.4 *_10
    - cdtime 3.1.3
    - cdutil 8.2
    - genutil 8.2
    - output_viewer 1.3.1
    - cibots 0.3
    - xarray 0.15.1
    - dask 2.15.0
    - lxml
    - sympy
    - pyproj 2.6.1.post1
    # can't bump until rasterio issue gets fixed
    - proj 7.0.0
    - pytest
    - shapely
    - cartopy
    - progressbar2
    - pillow
    - numpy >1.13
    - scipy
    - matplotlib
    - blas
    - nb_conda
    - nb_conda_kernels
    - plotly
    - bottleneck
    - hdf5 1.10.6 {{ mpi_prefix }}_*
    - libnetcdf 4.7.4 {{ mpi_prefix }}_*
    - netcdf4 1.5.3 nompi_*
    - pyevtk 1.1.2
    - f90nml
    - globus-sdk
    - tabulate
    - cmocean
    - gsw
    - pyflann
    - scikit-image
    - eofs 1.3.1
    - pywavelets
    - mpi4py  # [mpi != 'nompi']
    - pyremap
    - esmf 8.0.1 {{ mpi_prefix }}_*
    - openssh  # [mpi == 'openmpi']

test:
  requires:
    - pytest
  imports:
    - mpas_analysis
    - acme_diags
    - ILAMB  # [mpi != 'nompi']
    - zstash  # [linux]
    - IPython
    - globus_cli
    - livvkit
  commands:
    - mpas_analysis --version
    - livv --version
    - processflow -v  # [linux]
    - e3sm_diags --help
    - zstash --help  # [linux]
    - ilamb-fetch -h  # [mpi != 'nompi']
    - ilamb-run -h  # [mpi != 'nompi']
    - ilamb-table -h  # [mpi != 'nompi']
    - ncks --help
    - ncap2 --help
    - jupyter --help
    - jupyter nbextension list
    - ipython -h
    - ipython3 -h
    - globus --help
    - GenerateCSMesh --res 64 --alt --file gravitySam.000000.3d.cubedSphere.g
    - ESMF_RegridWeightGen --help

about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a unified conda environment for analysis of results
    from the Energy Exascale Earth System Model (E3SM).
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
