{% set name = "E3SM-Unified-HPC" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 2

requirements:
  host:
    - python {{ python }}
  run:
    ### main packages ###
    - python {{ python }}
    # channel: conda-forge
    - nco 4.8.1
    - jupyter
    - ipython
    - globus-cli
    - mpas-analysis 1.2.6
    # ilamb will be installed separately with --no-deps
    # to use system MPI and custom mpi4py
    #- ilamb 2.5
    - livvkit 2.1.6
    - geometric_features 0.1.4
    - mpas_tools 0.0.4
    - tempest-remap
    - ncl >=6.6.2
    # channel: cdat/label/v82
    - cdat 8.2
    # channel: e3sm
    - e3sm_diags 2.0.0
    - processflow 2.2.3 # [linux]
    - zstash 0.3.0 # [linux]
    ### dependencies ###
    # channel: cdat/lable/v82
    - vcsaddons 8.2
    - vtk-cdat 8.2.0.8.2
    - dv3d 8.2
    - vcs 8.2
    - wk 8.2
    # channel: conda-forge
    - cdat_info 8.2
    - cdms2 3.1.4
    - cdtime 3.1.2
    - cdutil 8.2
    - genutil 8.2
    - output_viewer 1.3.1
    - cibots 0.3
    - xarray 0.14.0
    - dask 2.6.0
    - distributed 2.6.0
    - lxml
    #- sympy
    - pyproj >=1.9.6,<2.0.0
    - proj4 >=5.2.0,<6.0.0
    - pytest
    - shapely
    #- cartopy
    - progressbar2
    - pillow
    - numpy >1.13
    #- scipy
    #- matplotlib
    - basemap
    - blas
    - nb_conda
    - nb_conda_kernels
    - plotly
    - bottleneck
    - hdf5 1.10.5
    - netcdf4 1.5.1.2
    - pyevtk 1.1.2
    - f90nml
    - globus-sdk
    - tabulate
    - cmocean
    - gsw
    - libnetcdf 4.6.2
    - pyflann
    - scikit-image
    - shapely
    - eofs 1.3.1
    - pywavelets
    - jigsaw
    - metis
    - pyflann
    - pyamg
    - ffmpeg
    - pyremap
    - esmf 7.1.0
    # ilamb dependencies except mpi4py
    - cartopy >=0.17.0
    - cf_units >=2.0.0
    - matplotlib >=2.2
    - openssh
    - scipy >=0.9.0
    - sympy >=0.7.6

test:
  requires:
    - pytest
  imports:
    - mpas_analysis
    - acme_diags
    #- ILAMB
    - zstash # [linux]
    - IPython
    - globus_cli
    - livvkit
  commands:
    - mpas_analysis --version
    - livv --version
    - export CDAT_ANONYMOUS_LOG=no; python -c "import vcs"
    - processflow -v # [linux]
    - e3sm_diags --help
    - zstash --help # [linux]
    #- ilamb-fetch -h
    #- ilamb-run -h
    #- ilamb-table -h
    - ncks --help
    - ncap2 --help
    - jupyter --help
    - jupyter nbextension list
    - ipython -h
    - ipython3 -h
    - globus --help
    - GenerateCSMesh --res 64 --alt --file gravitySam.000000.3d.cubedSphere.g
about:
  home: https://github.com/E3SM-Project/e3sm-unified
  summary: |
    A metapackage for a unified conda environment for analysis of results
    from the Energy Exascale Earth System Model (E3SM).
  dev_url: https://github.com/E3SM-Project/e3sm-unified

extra:
  recipe-maintainers:
    - xylar
