{% set name = "globus-cli" %}
{% set version = "1.2.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "2efb291ea03809e30d7e357955fbf777e6c2485cb61997656a314bf7695169f5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - globus = globus_cli:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - globus-sdk ==1.3.0
    - click >=6.6,<7.0
    - jmespath ==0.9.2
    - configobj >=5.0.6,<6.0.0
    - requests >=2.0.0,<3.0.0
    - six >=1.10.0,<2.0.0
  run:
    - python
    - globus-sdk ==1.3.0
    - click >=6.6,<7.0
    - jmespath ==0.9.2
    - configobj >=5.0.6,<6.0.0
    - requests >=2.0.0,<3.0.0
    - six >=1.10.0,<2.0.0

test:
  imports:
    - globus_cli
    - globus_cli.commands
    - globus_cli.commands.bookmark
    - globus_cli.commands.config
    - globus_cli.commands.endpoint
    - globus_cli.commands.endpoint.permission
    - globus_cli.commands.endpoint.role
    - globus_cli.commands.endpoint.server
    - globus_cli.commands.task
    - globus_cli.helpers
    - globus_cli.parsing
    - globus_cli.safeio
    - globus_cli.services
  commands:
    - globus --help

about:
  home: https://github.com/globus/globus-cli
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: Globus CLI
  description: ".. image:: https://travis-ci.org/globus/globus-cli.svg?branch=master\n    :alt: build status\n    :target: https://travis-ci.org/globus/globus-cli\n.. image:: https://badge.fury.io/py/globus-cli.svg\n\
    \    :alt: PyPi Version\n    :target: https://badge.fury.io/py/globus-cli\n.. image:: https://img.shields.io/pypi/pyversions/globus-cli.svg\n    :alt: Supported Pythons\n    :target: https://img.shields.io/pypi/pyversions/globus-cli.svg\n\
    \n\nGlobus CLI\n==========\n\nA Command Line Interface to `Globus <https://www.globus.org/>`_.\n\nSource Code: https://github.com/globusonline/globus-cli\n\nInstallation, Running, Other Documentation:\
    \ https://globus.github.io/globus-cli\n\nBugs and Feature Requests\n-------------------------\n\nBugs reports and feature requests are open submission, and should be filed at\nhttps://github.com/globusonline/globus-cli/issues"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: 'xylar'
